version: '3'

services:
  postgres:
    image: 'postgres:14'
    container_name: 'java_postgres'
    environment:
      - 'POSTGRES_USER=yerezhepsultan'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=demo_docker'

  app:
    build: ./
    container_name: 'java_app'
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/demo_docker'
#      - 'SPRING_DATASOURCE_USERNAME=yerezhepsultan'
#      - 'SPRING_DATASOURCE_PASSWORD='
#      - 'SPRING_JPA_HIBERNATE_DDL_AUTO=update'
